### ISSUE TITLE
Election generation models

### ISSUE THREAD

**Issue by simberaj** [simberaj/votelib#47]
[Tideman and Plassman (2010)](http://bingweb.binghamton.edu/~fplass/papers/ElectionGeneratingUniverse.pdf) list the following election generation models, e.g. Impartial Anonymous Culture (IAC). Implement them so that they produce random votes for election simulations.

**Comment by carlschroedl** [comment]
I skimmed this paper. It looks really interesting. I would be interested in reading it in detail and helping implement this issue. Unfortunately, the earliest I could start would be April. If you have time to do it sooner, that's OK -- go for it!

**Comment by simberaj** [comment]
I will gladly leave this up to you! I am not very well versed in the topic and will not have enough time in the near future to change that :-)

**Comment by simberaj** [comment]
@carlschroedl Have you had any time to look at this?

**Comment by carlschroedl** [comment]
Not yet. I am still interested in this, but I will be focusing elsewhere
for at least another month.

**Comment by simberaj** [comment]
I have created an initial version that should be generic enough. Specific models (IAC...) are yet to be implemented.
